### ISSUE TITLE
LibWeb Tracking Issue: Allow compilation on Lagom

### ISSUE THREAD

**Issue by Dexesttp** [SerenityOS/serenity#10968]
LibWeb would be extremely useful to have as a standalone component, especially for:
- Fuzzing the CSS and HTML parsers
- Running CI tests for LibWeb using Lagom (once we start having these tests)

The main blockers on this are LibWeb's reliance on LibGUI in some places of the code, and its reliance on IPC communications for contacting RequestServer.

Here are the current steps to unblock this:

- [x] Move the `DOMTreeModel` and `StylePropertiesModel` classes out of `LibWeb` (either in `Browser` directly or into their own library)
- [ ] Remove the reliance of `Page/EventHandler` and `Layout/{ButtonBox, CheckBox, Label, RadioButton}` on `LibGUI/Event.h` (we could keep it, but that's not very clean)
- [x] Move the `InProcessWebView`, `OutOfProcessWebView` and `WebContentClient` classes into their own library (this library will need a name)
- [x] Move the `LibProtocol/RequestClient` and `LibProtocol/WebSocketClient` usages that rely on IPC out of `LibWeb` - either by building a LibWeb-level abstraction or a IPC-level abstraction

**Comment by awesomekling** [comment]
I would suggest moving `DOMTreeModel` and `StylePropertiesModel` into the same library as `OutOfProcessWebView`.

**Comment by kleinesfilmroellchen** [comment]
Name suggestions (assuming in every step we choose the "new library" option, which I don't necessarily support):
1. LibDOM
3. LibWebView
4. LibWebNetworking, LibWebProtocol

I think it's a good idea to have LibWeb in the name of many/all of these, as they clearly belong with it. This is just bikeshedding though.

**Comment by kleinesfilmroellchen** [comment]
@Dexesttp is currently working on this.
