### ISSUE TITLE
"SerenityOS on SerenityOS" checklist

### ISSUE THREAD

**Issue by timschumi** [SerenityOS/serenity#12303]
This is a list of things that I noticed to be missing when trying to build SerenityOS inside SerenityOS (much less successfully building or running).

- [ ] Implement extended header support in `tar` (more precisely the path extensions for long file names)
- [ ] Support mapping files partially in `unzip`
- [ ] Implement selecting specific files for `unzip`
- [ ] Implement `install -D`

Most of these are currently worked around by additional patches ([serenity-on-serenity-host](https://github.com/timschumi/serenity/tree/serenity-on-serenity-host) for the modifications on the host, and [serenity-on-serenity](https://github.com/timschumi/serenity/tree/serenity-on-serenity) for the modifications for building), but obviously running patch-less is the target :^)

**Comment by circl-lastname** [comment]
Tar having XZ support would also need support for XZ in LibCompress

**Comment by IdanHo** [comment]
> Tar having XZ support would also need support for XZ in LibCompress

That is all that is needed for for xz support in Tar, "tar.foo" just means a tar file that is compressed with foo.

**Comment by circl-lastname** [comment]
Uh, I know, but Serenity doesn't support it in LibCompress yet, that's why there's a port of xz available

**Comment by ben-abraham** [comment]
One down :^) 

[Selecting specific files for unzip](https://github.com/SerenityOS/serenity/pull/12510)

**Comment by ben-abraham** [comment]
As a pre-requisite, we will need an LZMA2 implementation before we can support XZ archives. They work with a 'filter' mechanism that apply multiple modifiers to files increase the odds of getting good compression ratios.
[The filters that XZ has documented include:](https://tukaani.org/xz/xz-file-format.txt)
- LZMA2
- [6x] Branch/Call/Jump Filters for Executables
- Delta
- Custom
I would imagine most archives use, at a minimum, the LZMA2 layer, but I'm sure others are used somewhat commonly. Doing a super simple test on linux, the archive was created with only a single LZMA2 layer, and used CRC64 for checksums (another thing to add 😄).

**Comment by timschumi** [comment]
> As a pre-requisite, we will need an LZMA2 implementation before we can support XZ archives.

I believe @MaxWipfli is currently looking into this already. :^)

**Comment by MaxWipfli** [comment]
> > As a pre-requisite, we will need an LZMA2 implementation before we can support XZ archives.
> 
> I believe @MaxWipfli is currently looking into this already. :^)

Yes, I am working on it. I have only looked at decompression, which is already a pretty hefty task. I have almost fully implemented a basic usable version of the XZ container format and the beginnings of an LZMA2 decoder. I haven't really worked on the actual LZMA algorithm (which is a pain to implement due to a somewhat severe lack of documentation), but 
I already have basically everything *but* the actual LZMA algorithm done. This means that files only consisting of uncompressed LZMA chunks (e.g. very short files with less than ~20 bytes) are basically decompressable now. Should have a draft PR (without actual LZMA) ready soon-ish (hopefully later today).

**Comment by archanox** [comment]
SInce the ca changes had landed, I thought I'd give building SerenityOS a go.
![Uploading Screenshot from 2022-03-09 23-34-06.png…]()
As you can see in the attached screenshot there appears to be an issue with bintools not supporting the `--prefix` option, which I think has something to do with the shell?
Another thing of note is that the decompression of the gcc and binutils takes a considerable amount of time. Downloading from git also appears to take more time than expected.

**Comment by timschumi** [comment]
> As you can see in the attached screenshot there appears to be an issue with bintools not supporting the `--prefix` option, which I think has something to do with the shell?

Our `Shell` (which is symlinked to `/bin/sh`) is not POSIX-compatible, even though it should be. For now, you'll have to resort to building the `bash` port and symlinking `/bin/sh` to `/usr/local/bin/bash` in your `sync-local.sh`. That should also solve quite a few of the argument-related misconceptions that our own shell has.

> Another thing of note is that the decompression of the gcc and binutils takes a considerable amount of time. Downloading from git also appears to take more time than expected.

I haven't looked at profiling the decompression yet, but yeah, it takes very long. If you want to look into that, I'd greatly appreciate it. For testing, I modified my local copy to skip deleting the folder if it is already present, which considerably cuts down on time when restarting the build.

**Comment by archanox** [comment]
> Downloading from git also appears to take more time than expected.

I suspect something's iffy with the given message in the log
`[#0 NetworkTask(7:7)]: IPv4Socket(0xc34ab420): did_receive refusing packet since buffer is full.`
Which is spammed across the terminal when cloning from github

**Comment by timschumi** [comment]
> > Downloading from git also appears to take more time than expected.
> 
> I suspect something's iffy with the given message in the log `[#0 NetworkTask(7:7)]: IPv4Socket(0xc34ab420): did_receive refusing packet since buffer is full.` Which is spammed across the terminal when cloning from github

That should be handled by 0e970bba0a65db71c9d9ee193297f05a9a1e39de. While the message still appears occasionally, the cloning speed is much faster (and usually sufficient to handle the cloning speed that GitHub delivers on average).

**Comment by archanox** [comment]
The perl port is currently being tracked here https://github.com/SerenityOS/serenity/issues/1613

**Comment by archanox** [comment]
I've attempted another `rebuild-toolchain` with the latest changes to see where the current state of things are at.

With the default shell:
![image](https://user-images.githubusercontent.com/1642971/159492665-4a614e43-5081-4d1d-9f06-e303a6fa7cbd.png)

Similarly with bash:
![image](https://user-images.githubusercontent.com/1642971/159502340-10e53a8c-979f-45dd-b676-d01060a4b90b.png)

**Comment by timschumi** [comment]
Not surprising, the scripts use `/bin/sh` _everywhere_.

**Comment by BertalanD** [comment]
>  Make pick_gcc less annoying when building with Clang

#13677
