### ISSUE TITLE
Browser tracking issue: Test Browser on CI and publish the results

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#13379]
The reason this came up was that the German Wikipedia was reluctant to include a statement about Browser's Acid3 score in the SerenityOS page. The reason given there was basically: "it's a claim, not a proper source". A proper source would be objective, automatic, public test results. So that's what this issue and its PRs will track.

The goal is to have Browser (more specifically, a purpose-built minimal full-screen app that just has an OutOfProcessWebView) automatically test certain compliance pages, such as the three Acid tests or just generally hard web pages, as part of the normal CI tests. The tests take screenshots of the pages after some time, and the screenshots are extracted from the disk image + uploaded to a Serenity site (suggestion: serenityos.org/browser) daily. This will allow anyone to see and verify how the browser is currently looking on various websites.

Timeline:
* [ ] Implement virtual screens in WindowServer so that it can run without video hardware (PR incoming)
* [ ] Implement a test (framework) that does the on-target testing described above.
* [ ] Deal with the resultant images in CI and make them publicly available. (I'll need a lot of help for this!)

Tangentially related to #10968.
