### ISSUE TITLE
Toolchain: Upstreaming tracking for gcc/binutils/llvm

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#14183]
In order to be a fully accepted CMake target, we should have compiler support upstreamed to at least gcc or llvm-project.

Here's the list of things that need done for that do have a chance of succeeding:

Loader/Kernel/LibELF:
 - [ ] (Optional) Support tls-model other than initial-exec: Will remove a patch from each llvm and gcc
      - https://www.akkadia.org/drepper/tls.pdf

LibC:
 - [ ] Make`<ctype.h>` POSIX and C standard compliant. Remove hax from libc++ and libstdc++ patches pretending to be newlib.
 - [ ] (Optional) Unify libdl, libpthread, libc and libm into a mega-library to avoid cyclic dependencies in libstdc++
 - [ ] Remove _aligned_alloc and _aligned_free

GNU Autotools:
  - [x] config.sub
  - [x] config.guess
  - [ ] libtool.m4
  
Binutils:
     - [ ] Possibly find a way to remove the changed default base address of non-PIE executables? Ask on binutils mailing list if the patch is reasonable
   - [ ] Upstream the patch

GCC/libstdc++:
 - [ ] Split patch up
 - [ ] Upstream patches
 
 LLVM:
 - [ ] Remove _alligned_alloc patches
 - [ ] Remove patches from libc++ in `<initailizer_list>`
 - [ ] Upstream patches

**Comment by strnik12** [comment]
In order for `<ctype.h.>` to be POSIX compliant, doesn't `<locale.h>` have to also be POSIX compliant?

**Comment by ADKaster** [comment]
I believe our locale.h *is* compliant -- the C library only accepts the C locale.

The issue with ctype relates to us pretending to be newlib but not having the elements in the `_ctype_` global array arranged properly. LLVM chokes on it and we have to tell it to provide its own ctype.h

**Comment by ADKaster** [comment]
Turns out plenty of systems tell libc++ to provide its own "Rune table" ... so us doing so as well isn't that big a deal.

**Comment by ADKaster** [comment]
We should update the CMake patches to reflect the fact that LibDL is now an ld-script stub like Musl's by removing the LibDL lib variable from the Platform files.

**Comment by timschumi** [comment]
> LibDL is now an ld-script

Not sure if this is a typo, but better safe than sorry. Both LibDl and LibM are completely normal libraries at the moment, the only library that has been merged into LibC so far is LibPthread.

That said, I do plan to do the same with LibDl and LibM some time in the near future.

**Comment by ADKaster** [comment]
I created an RFC for LLVM upstreaming here: https://discourse.llvm.org/t/rfc-add-support-for-serenityos/71641

**Comment by alexrp** [comment]
FWIW, in order to be able to distribute Zig binaries for Serenity on https://ziglang.org/download (via https://codeberg.org/ziglang/zig-bootstrap), we'd need the following patches upstreamed:

* `0002-llvm-Add-support-for-building-LLVM-on-SerenityOS.patch`
* `0003-tools-Support-building-shared-libLLVM-and-libClang-f.patch`
* `0005-libcxx-Add-support-for-SerenityOS.patch`
* `0007-libcxxabi-Define-__cxa_thread_atexit-on-serenity.patch`

(The rest of the patches don't affect us.)

**Comment by LucasChollet** [comment]
Thanks for looking into this, always nice to see you guys checking on Serenity!
> in order to be able to distribute Zig binaries for Serenity

Though, I don't think that's a good idea, Serenity doesn't have a stable ABI so distributing binaries is a no-go.

That being said, I'm in the process of (slowly) upstreaming LLVM patches and I hope that the ones you listed will be in LLVM 23.

**Comment by alexrp** [comment]
As discussed in https://github.com/SerenityOS/serenity/issues/25941, the plan is to track a snapshot of Serenity master's libc ABI surface. Of course that means we're prone to occasional ABI breakage in Serenity, but it doesn't seem to happen often enough that it's likely to be a huge problem.

**Comment by LucasChollet** [comment]
Ah, I didn't remember it was discussed before. (And I didn't realize you were well aware of the issues, forget my comment then!)
