### ISSUE TITLE
"Things to not forget for the next toolchain update" checklist

### ISSUE THREAD

**Issue by timschumi** [SerenityOS/serenity#14347]
This is just a list of things that have queued up for the next "when we update toolchain" cycle and that we should keep track of.

## binutils

- [ ] Change [the default comment characters for the assembler](https://github.com/bminor/binutils-gdb/blob/49954a0d85403a7401efd95a648f39987da2a82b/gas/config/tc-i386.c#L479-L496), remove the workaround in the QEMU port if that has been merged by then.

## GCC

Nothing (yet).

## Clang

- [ ] Figure out if "[FIXME: Implement -static-libstdc++ in the next toolchain update](https://github.com/SerenityOS/serenity/blob/c6eaa39b990e2c654e09cc3bf7605de7ec7c13be/Meta/CMake/utils.cmake#L71)" still applies.
- [ ] Remove [Clang compatibility symlinks that have been duplicated into `Ports`](https://github.com/SerenityOS/serenity/blob/c6eaa39b990e2c654e09cc3bf7605de7ec7c13be/Ports/.hosted_defs.sh#L36-L41).

**Comment by ADKaster** [comment]
- Remove _aligned_alloc and _aligned_free from LibC and stdlib.h

**Comment by bgianfo** [comment]
Whoops, didn't see this on last toolchain update. 

Maybe we should mention this in a comment in the toolchain files... so folks don't mess it.
