### ISSUE TITLE
CMake: Tracking issue for CMake 3.25

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#14398]
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6837 merged on 2022-06-15 to add SerenityOS platform module support to upstream CMake.

Once an upstream CMake tag is created that includes https://gitlab.kitware.com/cmake/cmake/-/commit/c6e027cd5fab5b0986cd75ba7c7ad6f6a9cfe334 and a version > 3.24, pull it into the project.

- [x] Add Toolchain/BuildCMake.sh to build CMake 3.25 for the host if the host's package manager doesn't have 3.25 (very unlikely for at least a year, unless Arch btw).
- [x] Update CMake Port to 3.25 and remove Platform/ patches.
- [x] Ensure that local patches match upstream CMake for when user doesn't have 3.25 installed (should have a transition period, e.g. use latest and greatest CMake after X months. 3? 6?).

**Comment by AtkinsSJ** [comment]
Just checking, but I think this is complete now that we automatically build cmake 3.25.

**Comment by ADKaster** [comment]
Yep this is all set!
