### ISSUE TITLE
js: fuzzing results (that hit assertions)

### ISSUE THREAD

**Issue by Mindavi** [SerenityOS/serenity#1910]
I thought I'd share some of the results I got using fuzzing.

# Layout

First (1) the offending code is shown, then (2) the output of `js -A <file>` and lastly (3) the output of spidermonkey is shown.

Only examples for unresolved cases are shown, if someone resolves one of these, it would be nice if a test case was added that tests the case :smile:.

# Fixed cases

- [x] Return for (2 examples above)
- [x] Addition and `++` operator (PR #1911)
- [x] Whole lot of `+` signs
- [x] ToString `hasOwnProperty` (PR #2004)
- [x] For loop with undefined variable (PR #2006)
- [x] FlyString value empty (PR #2012)
- [x] to_number assertion (PR #2011)

## Returning the `for` keyword

1

```js
return for;
```

2

```
Syntax Error: Unexpected token For. Expected Semicolon (line: 1, column: 9)
Syntax Error: Unexpected token Semicolon. Expected ParenOpen (line: 1, column: 12)
js: /home/rick/hobby/serenity/Libraries/LibJS/Parser.cpp:935: NonnullRefPtr<JS::ForStatement> JS::Parser::parse_for_statement(): Assertion `false' failed.
Aborted (core dumped)
```

3

```
crashing-inputs/for:1:0 SyntaxError: return not in function:
crashing-inputs/for:1:0 return for;
crashing-inputs/for:1:0 ^
```

## Returning the for keyword v2

1

```js
function test() {
  return for;
}
```

2

```
Syntax Error: Unexpected token For. Expected Semicolon (line: 2, column: 10)
Syntax Error: Unexpected token Semicolon. Expected ParenOpen (line: 2, column: 13)
js: /home/rick/hobby/serenity/Libraries/LibJS/Parser.cpp:1002: NonnullRefPtr<JS::ForStatement> JS::Parser::parse_for_statement(): Assertion `false' failed.
Aborted (core dumped)
```

3

```
for2:2:9 SyntaxError: expected expression, got keyword 'for':
for2:2:9   return for;
for2:2:9 .........^
```

**Comment by linusg** [comment]
> I'm not sure if I should report the assertions that are hit, because they probably mean something is still TBD. However, I thought I'd share some of the results I got using fuzzing.

I still think reporting these is good, makes it easy to pick up something specific and fix it in the parser/AST :)

> They should all gracefully fail, I think.

Yes, definitely. No input, no matter how invalid, should make the interpreter crash - everything we don't understand should be a syntax error eventually.

---

Posting produced ASTs for completeness:

```
asse+++rt
```

```
Program
  (Children)
    ExpressionStatement
      BinaryExpression
        UpdateExpression
                    Identifier "asse"
          ++
        +
        Identifier "rt"
```

```
asse+++++++++++++++++++++++rt(typeof Object.prototype.toString() === "string");
```

```
Program
  (Children)
    ExpressionStatement
      BinaryExpression
        UpdateExpression
                    UpdateExpression
                        UpdateExpression
                            UpdateExpression
                                UpdateExpression
                                    UpdateExpression
                                        UpdateExpression
                                            UpdateExpression
                                                UpdateExpression
                                                    UpdateExpression
                                                        UpdateExpression
                                                            Identifier "asse"
                              ++
                            ++
                          ++
                        ++
                      ++
                    ++
                  ++
                ++
              ++
            ++
          ++
        +
        CallExpression 
          Identifier "rt"
          BinaryExpression
            UnaryExpression
              typeof 
              CallExpression 
                MemberExpression (computed=false)
                  MemberExpression (computed=false)
                    Identifier "Object"
                    Identifier "prototype"
                  Identifier "toString"
            ===
            StringLiteral "string"
```

**Comment by bugaevc** [comment]
> No input, no matter how invalid, should make the interpreter crash - everything we don't understand should be a syntax error eventually

In a perfect world, yes. But it's quite common in Serenity to put `ASSERT_NOT_REACHED()` on unimplemented code paths.

**Comment by linusg** [comment]
> But it's quite common in Serenity to put ASSERT_NOT_REACHED() on unimplemented code paths.

I know, hence "eventually" :wink:

---

Two more (`UpdateExpression`) cases crashing the interpreter.

---

```js
--foo++
```

```
Libraries/LibJS/AST.cpp:776: virtual JS::Value JS::UpdateExpression::execute(JS::Interpreter&) const: Assertion `m_argument->is_identifier()' failed.
```

```
Program
  (Children)
    ExpressionStatement
      UpdateExpression
        --
        UpdateExpression
                    Identifier "foo"
          ++
```

SpiderMonkey says:

```
SyntaxError: unexpected token: '++'
```

---


```js
++1 // Anything that's not an identifier basically: "", [], {}, true, false, null
```

```
Libraries/LibJS/AST.cpp:776: virtual JS::Value JS::UpdateExpression::execute(JS::Interpreter&) const: Assertion `m_argument->is_identifier()' failed.
```

```
Program
  (Children)
    ExpressionStatement
      UpdateExpression
        ++
        NumericLiteral 1
```

SpiderMonkey says:

```
SyntaxError: invalid increment/decrement operand
```

---

@Mindavi btw, "`asse+++rt`" is valid - it should just not crash if either `asse` or `rt` are not known, but throw a `ReferenceError` (This has been fixed). If both are known, it's basically doing `asse + rt; asse += 1`.

**Comment by linusg** [comment]
> I really have no idea why this crashes.

It's because `Array.prototype.toString()` can't handle circular references, and that function is being used in `Object::to_string()` which is being used in `Object::to_primitive()` which is being used for `==`.

So your example code can be simplified a bit and still crash:

```js
a = []
a[0] = a
a.toString()
```

A fix is pretty simple:

```diff

```

But that still crashes for "deep" circular references:

```js
a = []
b = []
a[0] = b
b[0] = a
a.toString()
```

We would probably need something like `js`'s `HashTable<JS::Object*>& seen_objects`.

Valgrind output:

```
==79300== Stack overflow in thread #1: can't grow stack to 0x1ffe801000
==79300== 
==79300== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==79300==  Access not within mapped region at address 0x1FFE801FD8
==79300== Stack overflow in thread #1: can't grow stack to 0x1ffe801000
==79300==    at 0x4633F3: JS::Object::to_string() const (Object.cpp:358)
==79300==  If you believe this happened as a result of a stack
==79300==  overflow in your program's main thread (unlikely but
==79300==  possible), you can try to increase the size of the
==79300==  main thread stack using the --main-stacksize= flag.
==79300==  The main thread stack size used in this run was 8388608.
==79300== Stack overflow in thread #1: can't grow stack to 0x1ffe801000
==79300== 
==79300== Process terminating with default action of signal 11 (SIGSEGV)
==79300==  Access not within mapped region at address 0x1FFE801FD0
==79300== Stack overflow in thread #1: can't grow stack to 0x1ffe801000
==79300==    at 0x483014D: _vgnU_freeres (vg_preloaded.c:59)
==79300==  If you believe this happened as a result of a stack
==79300==  overflow in your program's main thread (unlikely but
==79300==  possible), you can try to increase the size of the
==79300==  main thread stack using the --main-stacksize= flag.
==79300==  The main thread stack size used in this run was 8388608.
==79300== 
==79300== HEAP SUMMARY:
==79300==     in use at exit: 1,119,092 bytes in 18,465 blocks
==79300==   total heap usage: 31,314 allocs, 12,849 frees, 3,370,119 bytes allocated
==79300== 
==79300== LEAK SUMMARY:
==79300==    definitely lost: 0 bytes in 0 blocks
==79300==    indirectly lost: 0 bytes in 0 blocks
==79300==      possibly lost: 0 bytes in 0 blocks
==79300==    still reachable: 1,119,092 bytes in 18,465 blocks
==79300==                       of which reachable via heuristic:
==79300==                         newarray           : 53,816 bytes in 563 blocks
==79300==         suppressed: 0 bytes in 0 blocks
==79300== Rerun with --leak-check=full to see details of leaked memory
==79300== 
==79300== For lists of detected and suppressed errors, rerun with: -s
==79300== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by linusg** [comment]
> Conditional assignment hang/trashing

This is not specific to the ternary operator, rather the large number key is is the issue - in fact the same code with a small number works just fine. The issue is that we currently are resizing the underlying `Vector<Value>` and `555555555555555555555555555` empty `Value`s allocate a ton of memory.

> Integer overflow in array index

Same here.

SpiderMonkey has an efficient implementation for sparse arrays, that's why it works just fine - but _I believe_ `console.log` will still max out the CPU for a while as it has to go through all elements to stringify them.

**Comment by Mindavi** [comment]
Let's leave those out of here then. I already left things out like infinite recursion, because I guess it's obvious that isn't gonna work.

**Comment by Mindavi** [comment]
I'll have a new go at fuzzing LibJS tonight. However, it seems like the code is a lot less trigger-happy with the ASSERT_NOT_REACHED statements, so that's good. I have closes the last issue (`return for;`), which I figured would be fixed sooner rather than later. Let's close this and I'll open new issues when I find anything notable :).
