### ISSUE TITLE
Meta: Add gn build for lagom as an option to serenity.sh

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#23894]
The GN build (https://github.com/SerenityOS/serenity/tree/master/Meta/gn#readme) seems to be relatively stable at the moment. To promote more usage of the build, and get some experience for how nicely it plays with IDEs folks are using, we should add more integration for it into the normal build scripts.

- [ ] Add option for serenity.sh to use gn to create the build directory for Lagom. Likely in a separate build directory from the CMake build to avoid conflicts with the serenity build.
- [ ] Add code to generate a suitable ``args.gn`` on Linux systems. On macOS with homebrew, things will "just work". On Ubuntu, we need to run `qmake6 -query` to find the proper directories for Qt6 to build Ladybird, and to write down a suitable C++ compiler version.

Future goal:
- [ ] Use the JSON ide script output option for `gn gen` to generate CMake files good enough to make CLion happy.
