### ISSUE TITLE
LibWeb: Tracking issue for Filter Effects 1 specification

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#23943]
Uses of filter effects elements and functions in the wild include github.com's not-logged-in homepage.

https://drafts.fxtf.org/filter-effects-1/

Changes include:

- [ ] the "filter" property (https://drafts.fxtf.org/filter-effects-1/#FilterProperty)
- [ ] SVGFilterElement *https://drafts.fxtf.org/filter-effects-1/#FilterElement)
- [ ] All the filter primitives (feColorMatrix, feBlend, feGaussianBlur ...)
