### ISSUE TITLE
CMake: Overriding CMake Variables for cross-compile is fragile

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#4594]
As discussed in https://github.com/SerenityOS/serenity/issues/4569#issuecomment-751591680, the current strategy in CMakeList.txt of:

1) Running the host compiler to create host tools
2) Running host tools to autogenerate code
3) Changing all the CMake internal variables we can find until the cross compilation environment looks ok
4) Building all the target cross compiled libraries and applications (and kernel)

Is not a supported way to cross-compile in CMake. It just so happens to work (mostly), with the current version of CMake, on the targets we've tested for. Really, there should be at least a two stage CMake build, with separate CMake invocations for the host and target compiles. CMake was not designed to handle changing the compiler midway through.

We should do a few things:
 - [x] Create a CMake Toolchain file for the cross compiler environment https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html (#9297)
 - [x] Separate out steps that are supposed to be done with the host compiler vs the target compiler more explicitly (#9281)
 - [x] Invoke cmake from itself (?) or require a host-build/target-build set of build directories. (#9297)
 
 The second and third steps I'm not sure how to do, but as features are added, it will be a lot easier to build from different hosts if the main CMakeLists.txt isn't doing unsupported/undefined things to the poor CMake environment.

**Comment by Pagghiu** [comment]
Oh, I've been leaving a comment on another issue but it makes sense to have a dedicated discussion on the topic.
I've been proposing the same idea some time ago in #2519 but it was rejected entirely because of the convenience of keeping a single CMake build, even if this will cause a problems when building on any non Linux platform.

**Comment by ADKaster** [comment]
Hmm I remember seeing that PR. I think now that we've got shared libraries it's a good time to revisit whether having host options polluting the target build it a good idea. In my opinion, it's not, as it forces the kind of hacks I've put in #4582 with the shared library command. As well as the growing list of cmake variables to discover and unset. I think a two stage build in some form would remove all of that while being more "CMake-y".

I'm guessing @bugaevc will have an opinion here as well🙂.

**Comment by bugaevc** [comment]
This was previously discussed in https://github.com/SerenityOS/serenity/pull/2519.

> Is not a supported way to cross-compile in CMake. It just so happens to work (mostly), with the current version of CMake, on the targets we've tested for. Really, there should be at least a two stage CMake build, with separate CMake invocations for the host and target compiles. CMake was not designed to handle changing the compiler midway through.

It's true that upstream CMake [suggests using separate builds](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/CrossCompiling#using-executables-in-the-build-created-during-the-build). But I don't see why one cannot use different compilers / flags for different targets in the project — indeed, our current setup shows that it's very much possible to set different `CMAKE_CXX_COMPILER` and friends for different targets.

To make this work on Darwin hosts, we currently have to unset all the variables like `CMAKE_CXX_OSX_COMPATIBILITY_VERSION_FLAG` that get set by default when targeting Darwin. I recognise that that's not nice — does anybody know of a better way to do this (such as perhaps somehow only evaluating Darwin presets in a scope so that it doesn't pollute the global scope)?

Two-phase builds are IMHO an even bigger/uglier hack, and come with their own set of issues. Namely, that prevents CMake/Make/Ninja from properly tracing dependency chains across for-host and for-Serenity targets. It is my understanding that in a two-phase build, there's no single target dependency graph that includes all the build targets (generated code, binaries built for the host, binaries built for Serenity, etc.), instead there are multiple disjoint graphs.

So in that light, "keep a single build, just set the appropriate compiler & flags for each target" sounds like less of a hack than "do two builds with different compilers & flags" to me. Or are you suggesting it's still possible to keep a single graph while doing two-phase builds?

**Comment by ADKaster** [comment]
Thanks for the additional context on the previous discussion.

> Or are you suggesting it's still possible to keep a single graph while doing two-phase builds?

From my looking around yesterday, it *looks like* some combination of `ExternalProject_Add` and `exports` should allow for a completely different configuration for some build targets while maintaining a single dependency graph between them for partial builds?

I haven't prototyped such a configuration yet though. Seems like a worthwhile experiment to me.

@lanza was commenting on the MacOs build issue https://github.com/SerenityOS/serenity/issues/4569#issuecomment-751589381 that llvm uses a multi stage build for a few places, I'm curious how they've tackled the dependency graph problem. Or, if it was decided that having distinct builds was better than reconfiguring cmake in the middle of the build?

**Comment by lanza** [comment]
> It's true that upstream CMake suggests using separate builds. But I don't see why one cannot use different compilers / flags for different targets in the project — indeed, our current setup shows that it's very much possible to set different CMAKE_CXX_COMPILER and friends for different targets.

Scaling and reliability are my biggest concern with this. I don't work with Serenity on a regular basis, but I catch one of Andreas' YouTube videos a few times a month and something is usually flakey and/or broken with macOS builds. Anytime something new is done in CMake the question "how do we hack to make this work on macOS" has to be answered. Not to mention that the toolchain and cmake knowledge required to fix these things is pretty large. 

> @lanza was commenting on the MacOs build issue #4569 (comment) that llvm uses a multi stage build for a few places, I'm curious how they've tackled the dependency graph problem. Or, if it was decided that having distinct builds was better than reconfiguring cmake in the middle of the build?

`add_custom_command` and `add_custom_target` can be used to create any nodes in the dependency graph. Not to say this is an elegant solution by any means.

> To make this work on Darwin hosts, we currently have to unset all the variables like CMAKE_CXX_OSX_COMPATIBILITY_VERSION_FLAG that get set by default when targeting Darwin. I recognise that that's not nice — does anybody know of a better way to do this (such as perhaps somehow only evaluating Darwin presets in a scope so that it doesn't pollute the global scope)?

Nope, cmake does this when you call the `project` line. cmake maps a single invocation to a single build target. 

> So in that light, "keep a single build, just set the appropriate compiler & flags for each target" sounds like less of a hack than "do two builds with different compilers & flags" to me. Or are you suggesting it's still possible to keep a single graph while doing two-phase builds?

I don't consider the two separate builds to be a hack. It's pretty straight forward and since cmake upstream supports it thoroughly it's pretty well featured and complete. Building tools for the host platform relies on cmake's standard support and so the `ExternalProject` should work pretty flawlessly.

[Here is a pretty trivial example](https://github.com/lanza/cmake_sample) that builds the project twice -- once for the main target and once for the "Host" tool. The main target uses the host tool to produce `Result`.

**Comment by friendlyanon** [comment]
@bugaevc Actually, it's very easy to manage a monorepo with host-only subprojects. You need to create a superbuild lists file that the developers can use for convenience, something like this:

<details>

```cmake
cmake_minimum_required(VERSION 3.16)

project(
    SerenitySuperbuild
    DESCRIPTION "Orchestrate host and target builds in a single build"
    LANGUAGES NONE
)

# Assuming this file is Meta/CMake/Superbuild/CMakeLists.txt
get_filename_component(
    SERENITY_PROJECT_ROOT "${PROJECT_SOURCE_DIR}/../../.."
    ABSOLUTE CACHE
)

include(ExternalProject)

ExternalProject_Add(
    host-tools
    SOURCE_DIR "${SERENITY_PROJECT_ROOT}/wherever/the/tools/are"
    BINARY_DIR "${PROJECT_BINARY_DIR}/host-build"
    INSTALL_DIR "${PROJECT_BINARY_DIR}/host-install"
    CMAKE_CACHE_DEFAULT_ARGS
    -DFOO:STRING=BAR
    -DAYY:STRING=LMAO
    # Always call the build step of tools, so keeping things up-to-date is easy
    BUILD_ALWAYS YES
    # Make the test step available, but make it manual
    TEST_EXCLUDE_FROM_MAIN NO
    # Expose install step as a target, so it can be depended on
    STEP_TARGETS install
)

ExternalProject_Add(
    target
    SOURCE_DIR "${SERENITY_PROJECT_ROOT}/wherever/the/OS/is"
    BINARY_DIR "${PROJECT_BINARY_DIR}/target-build"
    CMAKE_CACHE_DEFAULT_ARGS
    # Tell the find_package(SerenityHost REQUIRED) command call where to find
    # the CMake package
    "-DCMAKE_PREFIX_PATH:STRING=${PROJECT_BINARY_DIR}/host-install"
    "-DCMAKE_TOOLCHAIN_FILE:STRING=${SOME_VARIABLE_FOR_TOOLCHAIN_FILE}"
    # Always call the build step
    BUILD_ALWAYS YES
    # Host tools must be built and installed before the OS can be built
    DEPENDS host-tools-install
)
```

</details>

Using this lists file I could achieve such a build:

```
λ cmake --build build
...
[14/16] Performing build step for 'target'
[1/1] Running host tool
Hello from host!
[16/16] Completed 'target'
```

After editing one source file in the host tool:

```
λ cmake --build build
...
[4/6] Performing build step for 'target'
[1/1] Running host tool
Hello from host! :^)
[6/6] Completed 'target'
```

With this setup, you can use your usual workflow, except instead of `cd`ing into the build dir, you `cd` into either the `<binary-dir>/target-build` or `<binary-dir>/host-build`. If you want to make sure things build if you are changing things in both, then you can just `ninja -C ..` from either of those directories. If you want to change CMake options around, you can just `ccmake .` in either of them.

Hacking your way around this is always going to just cause issues, it's better to keep the host and target builds separate, then use some mechanism to pair them up. `ExternalProject` is sufficient for this goal.

This would of course require that both the host and target subprojects are well-behaved CMake projects and SerenityOS's lists files could use some cleaning up, for example there are a lot of things in the lists files at the moment that are neither build nor usage requirements, so these should be moved somewhere outside them.  
For this one [presets](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) can be used to very efficiently solve this problem. Note that use of presets by developers does **not** require raising the version in the `cmake_minimum_required()` command calls, because it's just one way to keep things in one place that you otherwise would have to pass via the CLI or by using scripts to invoke CMake. `cmake_minimum_required()` should only indicate what features and policies are in use in the lists files themselves.

**Comment by ADKaster** [comment]
Hey @friendlyanon  I was taking a look at this issue again and had a couple questions about your example superbuild file.

<details>

<summary> My edits in here vvv </summary>

cmake_minimum_required(VERSION 3.16)

project(
    SerenitySuperbuild
    DESCRIPTION "Orchestrate host and target builds in a single build"
    LANGUAGES NONE
)

# FIXME: What is this for? We don't use DEBUG/RELEASE at all, so can probably be ignored?
get_cmake_property(is_multi_config GENERATOR_IS_MULTI_CONFIG)
set(config "-DCMAKE_BUILD_TYPE:STRING=$<CONFIG>")
if(is_multi_config)
  set(config "")
endif()

# Assuming this file is Meta/CMake/Superbuild/CMakeLists.txt
get_filename_component(
    SERENITY_PROJECT_ROOT "${PROJECT_SOURCE_DIR}/../../.."
    ABSOLUTE CACHE
)

get_filename_component(
    SERENITY_TOOLCHAIN_FILE "${SERENITY_PROJECT_ROOT}/Toolchain/CMake/CMakeToolchain.txt"
    ABSOLUTE CACHE
)

include(ExternalProject)

set_property(DIRECTORY PROPERTY EP_PREFIX "${PROJECT_BINARY_DIR}/ep-prefix")

ExternalProject_Add(
    lagom
    SOURCE_DIR "${SERENITY_PROJECT_ROOT}/Meta/Lagom"
    BINARY_DIR "${PROJECT_BINARY_DIR}/lagom-build"
    INSTALL_DIR "${PROJECT_BINARY_DIR}/lagom-install"
    EXCLUDE_FROM_ALL YES
    CMAKE_CACHE_DEFAULT_ARGS
    ${config}
    -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
    # Always call the build step of tools, so keeping things up-to-date is easy
    BUILD_ALWAYS YES
    # Expose install step as a target, so it can be depended on
    STEP_TARGETS install
)

ExternalProject_Add(
    target
    SOURCE_DIR "${SERENITY_PROJECT_ROOT}"
    BINARY_DIR "${PROJECT_BINARY_DIR}/target-build"
    CMAKE_CACHE_DEFAULT_ARGS
    ${config}
    # Tell the find_package(SerenityHost REQUIRED) command call where to find
    # the CMake package
    "-DCMAKE_PREFIX_PATH:STRING=${PROJECT_BINARY_DIR}/lagom-install"
    "-DCMAKE_TOOLCHAIN_FILE:STRING=${SERENITY_TOOLCHAIN_FILE}"
    # Always call the build step
    BUILD_ALWAYS YES
    # Host tools must be built and installed before the OS can be built
    DEPENDS lagom-install
)

</details>

1) Where does the find_package(SerenityHost REQUIRED) come in? Would we drop that statement at the top of the top level CMakeLists.txt? Where does its name come from? (i.e. do we need a Meta/CMake/SerenityHost.cmake file?)

---

2) I'm assuming as part of this exercise that we'd want to move all of the code generators into the "host build" CMakeLists.txt? 

So all of this

```
add_subdirectory(Meta/Lagom)
add_subdirectory(Userland/DevTools/IPCCompiler)
add_subdirectory(Userland/DevTools/StateMachineGenerator)
add_subdirectory(Userland/Libraries/LibWeb/CodeGenerators)
add_subdirectory(Meta/CMake/ConfigureComponents)
```

Will go into the "host build" CMakeLists?

---

3) How do we access the host tool from the target build?

For example, the IPC Compiler CMakeLists.txt looks like this:
```
set(SOURCES
    main.cpp
)

add_executable(IPCCompiler ${SOURCES})
target_link_libraries(IPCCompiler LagomCore)
```

And the generator like this:

```
function(compile_ipc source output)
    set(source ${CMAKE_CURRENT_SOURCE_DIR}/${source})
    add_custom_command(
        OUTPUT ${output}
        COMMAND ${write_if_different} ${output} ${CMAKE_BINARY_DIR}/Userland/DevTools/IPCCompiler/IPCCompiler ${source}
        VERBATIM
        DEPENDS IPCCompiler
        MAIN_DEPENDENCY ${source}
    )
    get_filename_component(output_name ${output} NAME)
    add_custom_target(generate_${output_name} DEPENDS ${output})
endfunction()
```

So we would change the path to it to be like... "${CMAKE_BINARY_DIR}/lagom-install/IPCCompiler/IPCCompiler" ?

Or would it be some sort of "lagom::IPCCompiler" exported/namespaced target we could use?

---

4) Do all of the CMake options we have go in the SuperBuild CMakeListst, or in the Host/Target top level ones? And, do the options get automatically passed down to the external projects? or do we have to pass them one by one?

**Comment by friendlyanon** [comment]
> `# FIXME: What is this for? We don't use DEBUG/RELEASE at all, so can probably be ignored?`

It's generally a good idea to specify the build type, because it enables the use of some features of CMake, like config dependent flags, imported target mapping, etc. For the host tools it's definitely a good idea to use release builds, just because I would assume that you want faster builds. For the target platform project, you can customize things cleanly with the toolchain file as well. I have made [some](https://old.reddit.com/r/cpp/comments/ooltio/cmake_part_1_the_dark_arts_cmake_and_embedded_c/h5zy5po/) [comments](https://old.reddit.com/r/cpp/comments/oqlc48/cmake_part_2_release_and_debug_builds/h6csz6c/) regarding toolchains that might be of use to you.

---

The name `SerenityHost` was merely an example. I have not actually looked at the build files for Serenity yet.

---

Not just code generators, but ideally you'd want to partition the build in a way that the tools (any tool) that must run on the host are built in a host project and then those tools are fed into the next build that requires them.

---

The way you access a host tool from a target platform project is by using the CMake package mechanism of CMake, for which you need proper [install rules](https://github.com/friendlyanon/cmake-init-executable/blob/master/cmake/install-rules.cmake) defined. This is why the host tool in my example has the install prefix passed to it as `-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>` (in which `<INSTALL_DIR>` is an `ExternalProject` specific placeholder for the `INSTALL_DIR` argument) and the target platform project has `"-DCMAKE_PREFIX_PATH:STRING=${PROJECT_BINARY_DIR}/host-install"` passed to it, which enables a `find_package` call to find that installed package in the provided prefix. If we take the previously linked install rules, then after finding the package, you'd have the `executable::executable` target available to you that you can use in custom commands and custom targets to generate code for you.

---

The options situation is a tricky one. I guess it depends on how much you want to provide up front. Like I said, you can just `cd` into the `BINARY_DIR`s of the individual projects and `ccmake .` or `cmake . -Dvar=val`, but if you want to "force" some values then you can use the `CMAKE_CACHE_ARGS` argument in the superbuild lists file, which is the equivalent of passing `-Dvar=val` to the configure commands.

**Comment by friendlyanon** [comment]
@ADKaster here I have a practical example of a superbuild in use for fuzz testing: https://github.com/friendlyanon/cmake-init-gif-engine/blob/master/fuzz/CMakeLists.txt

**Comment by ADKaster** [comment]
Unresolved Feedback/FIXMEs from #9017:

---


Lagom targets should have `target_include_directories` set such that libjs-test262 doesn't have to specify include directories when linking against Lagom libraries when doing FetchContent.

https://github.com/linusg/libjs-test262/pull/30#discussion_r679102040

> If the targets made available from Lagom have their includes properly setup, then it's unnecessary to do this.
Proper meaning that the targets use PUBLIC requirement modifier, i.e. both INCLUDE_DIRECTORIES and INTERFACE_INCLUDE_DIRECTORIES get populated and it's the INTERFACE_* properties that propagate requirements. You might also want a conditional SYSTEM modifier to exclude warnings from vendored sources. Example.

> Making a project FetchContent-ready takes a bit more effort, however.

----

We should avoid providing `$<TARGET_OBJECTS:SomeObjectTarget>` as build rules, because one can simply target_link_libraries against `SomeObjectTarget`. This mostly applies to `serenity_test` and `serentiy_libjs_test` build rules.

https://github.com/SerenityOS/serenity/pull/9017#discussion_r678194791


---

Avoid confusing ALIAS targets with install names. To allow for easier FetchContent for other possible downstream projects (wasm-spec-tests repo + website anyone?), we should take care that the ALIAS targets match the install name exactly.

https://github.com/SerenityOS/serenity/pull/9017#discussion_r679231075

---

Multiple FIXMEs entered the Lagom/CMakeLists.txt, mostly concerning avoiding creating install rules when the lagom build dir is add_subdirectory'd from the serenity target build before the toolchain swaparoo.

---
