### ISSUE TITLE
Boot: Support diskless and network booting

### ISSUE THREAD

**Issue by boricj** [SerenityOS/serenity#5013]
I'm thinking about booting SerenityOS on my old PC (Athlon XP-class processor on an A7N8X-E Deluxe motherboard), but I'm too lazy to deal with old ATA drives and IDE emulation nonsense... Time to boot SerenityOS over the network with a ramdisk.

I want to netboot SerenityOS because I don't want to deal with local storage on the target during a bringup on hardware. Therefore, I also need to use ramdisks because SerenityOS currently doesn't support anything for the root file system but ext2 on an IDE controller.

Tasks identified so far:
- [X] Fix multiboot compliance issues (#5002)
- [x] Move kmalloc's eternal heap inside the kernel's .bss segment (#5028)
- [x] Move super physical page pool inside the kernel's .bss segment (#5028)
- [x] Parse multiboot header for boot modules and keep track of them (#5028)
- [x] Create ramdisk block devices from boot modules and hook them inside DevFS (#5028)
- [x] Add support for ramdisks as a boot device (#5028)
- [X] Get diskless boot to work
- [X] Get network boot to work (works, but suffers from unrelated issues in the system)
- [x] Document that stuff (#5108)
