### ISSUE TITLE
LibC: Wine checklist

### ISSUE THREAD

**Issue by sin-ack** [SerenityOS/serenity#6410]
This is a list of things that need to be implemented in order get Wine running. Note that we still need to implement a display backend for `WindowServer` as Wine uses X11 directly, and also an `AudioServer` connection for audio playback. Most of this functionality is required by the `dlls/ntdll/unix/` directory since that seems to be where all the platform-related functionality is residing.

This list also isn't complete because it's just what I gathered from running `make --keep-going` so we might need other things.

- [x] `n_long`/`n_short` (Linux puts these in `<netinet/in_systm.h>`) - `dlls/iphlpapi/icmp.c`
- [ ] `IPPROTO_ICMPV6` and `IP_TTL` (`<netinet/in.h>`) - `dlls/iphlpapi/icmp.c`
- [x] `<langinfo.h>` - `dlls/ntdll/unix/env.c`
- [x] `MSG_PEEK` (`<socket.h>`) - `dlls/ntdll/unix/file.c`
- [ ] `statvfs` and associated data structures (tracked in #6068) - `dlls/ntdll/unix/file.c`
- [ ] `rlimit` related functionality (`<unistd.h>`) - `dlls/ntdll/unix/loader.c`
- [x] `Dl_info`, `dladdr` (`<dlfcn.h>`) - `dlls/ntdll/unix/loader.c`
  (Most of the dynamic linker stuff seems to be implemented already, and just needs to be exposed)
- [ ] ELF related things (`AT_PHDR`, `AT_PHENT`, `AT_PHNUM`, `Elf32_Phdr`) - `dlls/ntdll/unix/loader.c`
- [ ] Signal context functions (`ucontext_t` and friends) - `dlls/ntdll/unix/signal_i386.c`
- [x] `pthread_addr_setscope` and `PTHREAD_SCOPE_SYSTEM` - `dlls/ntdll/unix/thread.c`
- [ ] Exposing `struct iovec` - `dlls/ntdll/unix/virtual.c`
- [ ] `mlock`/`munlock` and `madvise` - `dlls/ntdll/unix/virtual.c`

**Comment by Hendiadyoin1** [comment]
n_long and n_short seem to be just typedefines for u32 and u16 respectivly, with the caviats that they are supposed to be guaranteed to be in big endian ("high-ender" order) if I understand it correctly

**Comment by Hendiadyoin1** [comment]
`<netinet/in_systm.h>`seems to declare another funciton called iptime(), but I only found that in BSD, is that required too

it grabs a `timeval` with `getmicrotime(timeval*) /*BSD specific, again]*/` and converts it into the right format for `n_time` ie ms since GMT 00:00 (I guess start of the day?)

**Comment by kevodwyer** [comment]
Another option is to run Wine via #6637

**Comment by gunnarbeutner** [comment]
Btw, #7844 implements `dladdr()`. :partying_face:

**Comment by bgianfo** [comment]
And, #6527 added `pthread_addr_setscope` stubs.

**Comment by sin-ack** [comment]
Closing this as it's very old and is not up-to-dodate with the current state of Wine support in Serenity (it actually builds now). Someone who is more involved should open a new tracker issue.
