### ISSUE TITLE
Meta: pkgsrc bootstrapping progress

### ISSUE THREAD

**Issue by boricj** [SerenityOS/serenity#8605]
This is a meta-issue to track progress on bootstrapping pkgsrc on SerenityOS. While I don't expect it to replace the native Ports systems, it's a good stress test of both POSIX conformance, performance and stability.

Blocked on:
- [x] #8473 Storage stack issues with large partition sizes
- [x] #8567 Various small POSIX compliance issues
- [ ] #8506 expr POSIX compliance
