### ISSUE TITLE
UserlspaceEmulator: x86_64 checklist

### ISSUE THREAD

**Issue by Hendiadyoin1** [SerenityOS/serenity#8872]
1. [ ] buildability
2. [ ] REX prefix and extended registers
3. [ ] add all behavior for REX prefix
4. [ ] SSE (starting at opcodes)
    1. [ ] SEE Op codes
    2. [ ] SSE implemetation
5. [ ] FPU env fixup (depends on the FPU pull)
6. [ ] all the things I forgot
