### ISSUE TITLE
LibJS: Temporal proposal progress tracking

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#8982]
Spec: https://tc39.es/proposal-temporal/

- [x] Temporal [ @@toStringTag ]
- [x] Temporal.Now [ @@toStringTag ]
- [x] Temporal.Now.timeZone
- [x] Temporal.Now.instant
- [x] Temporal.Now.plainDateTime
- [x] Temporal.Now.plainDateTimeISO
- [x] Temporal.Now.zonedDateTime
- [x] Temporal.Now.zonedDateTimeISO
- [x] Temporal.Now.plainDate
- [x] Temporal.Now.plainDateISO
- [x] Temporal.Now.plainTimeISO
- [x] Temporal.PlainDate
- [x] Temporal.PlainDate.from
- [x] Temporal.PlainDate.compare
- [x] Temporal.PlainDate.prototype.constructor
- [x] Temporal.PlainDate.prototype[ @@toStringTag ]
- [x] Temporal.PlainDate.prototype.calendar
- [x] Temporal.PlainDate.prototype.year
- [x] Temporal.PlainDate.prototype.month
- [x] Temporal.PlainDate.prototype.monthCode
- [x] Temporal.PlainDate.prototype.day
- [x] Temporal.PlainDate.prototype.dayOfWeek
- [x] Temporal.PlainDate.prototype.dayOfYear
- [x] Temporal.PlainDate.prototype.weekOfYear
- [x] Temporal.PlainDate.prototype.daysInWeek
- [x] Temporal.PlainDate.prototype.daysInMonth
- [x] Temporal.PlainDate.prototype.daysInYear
- [x] Temporal.PlainDate.prototype.monthsInYear
- [x] Temporal.PlainDate.prototype.inLeapYear
- [x] Temporal.PlainDate.prototype.toPlainYearMonth
- [x] Temporal.PlainDate.prototype.toPlainMonthDay
- [x] Temporal.PlainDate.prototype.getISOFields
- [x] Temporal.PlainDate.prototype.add
- [x] Temporal.PlainDate.prototype.subtract
- [x] Temporal.PlainDate.prototype.with
- [x] Temporal.PlainDate.prototype.withCalendar
- [x] Temporal.PlainDate.prototype.until
- [x] Temporal.PlainDate.prototype.since
- [x] Temporal.PlainDate.prototype.equals
- [x] Temporal.PlainDate.prototype.toPlainDateTime
- [x] Temporal.PlainDate.prototype.toZonedDateTime
- [x] Temporal.PlainDate.prototype.toString
- [x] Temporal.PlainDate.prototype.toLocaleString
- [x] Temporal.PlainDate.prototype.toJSON
- [x] Temporal.PlainDate.prototype.valueOf
- [x] Temporal.PlainTime
- [x] Temporal.PlainTime.from
- [x] Temporal.PlainTime.compare
- [x] Temporal.PlainTime.prototype.constructor
- [x] Temporal.PlainTime.prototype[ @@toStringTag ]
- [x] Temporal.PlainTime.prototype.calendar
- [x] Temporal.PlainTime.prototype.hour
- [x] Temporal.PlainTime.prototype.minute
- [x] Temporal.PlainTime.prototype.second
- [x] Temporal.PlainTime.prototype.millisecond
- [x] Temporal.PlainTime.prototype.microsecond
- [x] Temporal.PlainTime.prototype.nanosecond
- [x] Temporal.PlainTime.prototype.add
- [x] Temporal.PlainTime.prototype.subtract
- [x] Temporal.PlainTime.prototype.with
- [x] Temporal.PlainTime.prototype.until
- [x] Temporal.PlainTime.prototype.since
- [x] Temporal.PlainTime.prototype.round
- [x] Temporal.PlainTime.prototype.equals
- [x] Temporal.PlainTime.prototype.toPlainDateTime
- [x] Temporal.PlainTime.prototype.toZonedDateTime
- [x] Temporal.PlainTime.prototype.getISOFields
- [x] Temporal.PlainTime.prototype.toString
- [x] Temporal.PlainTime.prototype.toLocaleString
- [x] Temporal.PlainTime.prototype.toJSON
- [x] Temporal.PlainTime.prototype.valueOf
- [x] Temporal.PlainDateTime
- [x] Temporal.PlainDateTime.from
- [x] Temporal.PlainDateTime.compare
- [x] Temporal.PlainDateTime.prototype.constructor
- [x] Temporal.PlainDateTime.prototype[ @@toStringTag ]
- [x] Temporal.PlainDateTime.prototype.calendar
- [x] Temporal.PlainDateTime.prototype.year
- [x] Temporal.PlainDateTime.prototype.month
- [x] Temporal.PlainDateTime.prototype.monthCode
- [x] Temporal.PlainDateTime.prototype.day
- [x] Temporal.PlainDateTime.prototype.hour
- [x] Temporal.PlainDateTime.prototype.minute
- [x] Temporal.PlainDateTime.prototype.second
- [x] Temporal.PlainDateTime.prototype.millisecond
- [x] Temporal.PlainDateTime.prototype.microsecond
- [x] Temporal.PlainDateTime.prototype.nanosecond
- [x] Temporal.PlainDateTime.prototype.dayOfWeek
- [x] Temporal.PlainDateTime.prototype.dayOfYear
- [x] Temporal.PlainDateTime.prototype.weekOfYear
- [x] Temporal.PlainDateTime.prototype.daysInWeek
- [x] Temporal.PlainDateTime.prototype.daysInMonth
- [x] Temporal.PlainDateTime.prototype.daysInYear
- [x] Temporal.PlainDateTime.prototype.monthsInYear
- [x] Temporal.PlainDateTime.prototype.inLeapYear
- [x] Temporal.PlainDateTime.prototype.with
- [x] Temporal.PlainDateTime.prototype.withPlainTime
- [x] Temporal.PlainDateTime.prototype.withPlainDate
- [x] Temporal.PlainDateTime.prototype.withCalendar
- [x] Temporal.PlainDateTime.prototype.add
- [x] Temporal.PlainDateTime.prototype.subtract
- [x] Temporal.PlainDateTime.prototype.until
- [x] Temporal.PlainDateTime.prototype.since
- [x] Temporal.PlainDateTime.prototype.round
- [x] Temporal.PlainDateTime.prototype.equals
- [x] Temporal.PlainDateTime.prototype.toString
- [x] Temporal.PlainDateTime.prototype.toLocaleString
- [x] Temporal.PlainDateTime.prototype.toJSON
- [x] Temporal.PlainDateTime.prototype.valueOf
- [x] Temporal.PlainDateTime.prototype.toZonedDateTime
- [x] Temporal.PlainDateTime.prototype.toPlainDate
- [x] Temporal.PlainDateTime.prototype.toPlainYearMonth
- [x] Temporal.PlainDateTime.prototype.toPlainMonthDay
- [x] Temporal.PlainDateTime.prototype.toPlainTime
- [x] Temporal.PlainDateTime.prototype.getISOFields
- [x] Temporal.ZonedDateTime
- [x] Temporal.ZonedDateTime.from
- [x] Temporal.ZonedDateTime.compare
- [x] Temporal.ZonedDateTime.prototype.constructor
- [x] Temporal.ZonedDateTime.prototype[ @@toStringTag ]
- [x] Temporal.ZonedDateTime.prototype.calendar
- [x] Temporal.ZonedDateTime.prototype.timeZone
- [x] Temporal.ZonedDateTime.prototype.year
- [x] Temporal.ZonedDateTime.prototype.month
- [x] Temporal.ZonedDateTime.prototype.monthCode
- [x] Temporal.ZonedDateTime.prototype.day
- [x] Temporal.ZonedDateTime.prototype.hour
- [x] Temporal.ZonedDateTime.prototype.minute
- [x] Temporal.ZonedDateTime.prototype.second
- [x] Temporal.ZonedDateTime.prototype.millisecond
- [x] Temporal.ZonedDateTime.prototype.microsecond
- [x] Temporal.ZonedDateTime.prototype.nanosecond
- [x] Temporal.ZonedDateTime.prototype.epochSeconds
- [x] Temporal.ZonedDateTime.prototype.epochMilliseconds
- [x] Temporal.ZonedDateTime.prototype.epochMicroseconds
- [x] Temporal.ZonedDateTime.prototype.epochNanoseconds
- [x] Temporal.ZonedDateTime.prototype.dayOfWeek
- [x] Temporal.ZonedDateTime.prototype.dayOfYear
- [x] Temporal.ZonedDateTime.prototype.weekOfYear
- [x] Temporal.ZonedDateTime.prototype.hoursInDay
- [x] Temporal.ZonedDateTime.prototype.daysInWeek
- [x] Temporal.ZonedDateTime.prototype.daysInMonth
- [x] Temporal.ZonedDateTime.prototype.daysInYear
- [x] Temporal.ZonedDateTime.prototype.monthsInYear
- [x] Temporal.ZonedDateTime.prototype.inLeapYear
- [x] Temporal.ZonedDateTime.prototype.offsetNanoseconds
- [x] Temporal.ZonedDateTime.prototype.offset
- [x] Temporal.ZonedDateTime.prototype.with
- [x] Temporal.ZonedDateTime.prototype.withPlainTime
- [x] Temporal.ZonedDateTime.prototype.withPlainDate
- [x] Temporal.ZonedDateTime.prototype.withTimeZone
- [x] Temporal.ZonedDateTime.prototype.withCalendar
- [x] Temporal.ZonedDateTime.prototype.add
- [x] Temporal.ZonedDateTime.prototype.subtract
- [x] Temporal.ZonedDateTime.prototype.until
- [x] Temporal.ZonedDateTime.prototype.since
- [x] Temporal.ZonedDateTime.prototype.round
- [x] Temporal.ZonedDateTime.prototype.equals
- [x] Temporal.ZonedDateTime.prototype.toString
- [x] Temporal.ZonedDateTime.prototype.toLocaleString
- [x] Temporal.ZonedDateTime.prototype.toJSON
- [x] Temporal.ZonedDateTime.prototype.valueOf
- [x] Temporal.ZonedDateTime.prototype.startOfDay
- [x] Temporal.ZonedDateTime.prototype.toInstant
- [x] Temporal.ZonedDateTime.prototype.toPlainDate
- [x] Temporal.ZonedDateTime.prototype.toPlainTime
- [x] Temporal.ZonedDateTime.prototype.toPlainDateTime
- [x] Temporal.ZonedDateTime.prototype.toPlainYearMonth
- [x] Temporal.ZonedDateTime.prototype.toPlainMonthDay
- [x] Temporal.ZonedDateTime.prototype.getISOFields
- [x] Temporal.Duration
- [x] Temporal.Duration.from
- [x] Temporal.Duration.compare
- [x] Temporal.Duration.prototype.constructor
- [x] Temporal.Duration.prototype[ @@toStringTag ]
- [x] Temporal.Duration.prototype.years
- [x] Temporal.Duration.prototype.months
- [x] Temporal.Duration.prototype.weeks
- [x] Temporal.Duration.prototype.days
- [x] Temporal.Duration.prototype.hours
- [x] Temporal.Duration.prototype.minutes
- [x] Temporal.Duration.prototype.seconds
- [x] Temporal.Duration.prototype.milliseconds
- [x] Temporal.Duration.prototype.microseconds
- [x] Temporal.Duration.prototype.nanoseconds
- [x] Temporal.Duration.prototype.sign
- [x] Temporal.Duration.prototype.blank
- [x] Temporal.Duration.prototype.with
- [x] Temporal.Duration.prototype.negated
- [x] Temporal.Duration.prototype.abs
- [x] Temporal.Duration.prototype.add
- [x] Temporal.Duration.prototype.subtract
- [x] Temporal.Duration.prototype.round
- [x] Temporal.Duration.prototype.total
- [x] Temporal.Duration.prototype.toString
- [x] Temporal.Duration.prototype.toJSON
- [x] Temporal.Duration.prototype.toLocaleString
- [x] Temporal.Duration.prototype.valueOf
- [x] Temporal.Instant
- [x] Temporal.Instant.from
- [x] Temporal.Instant.fromEpochSeconds
- [x] Temporal.Instant.fromEpochMilliseconds
- [x] Temporal.Instant.fromEpochMicroseconds
- [x] Temporal.Instant.fromEpochNanoseconds
- [x] Temporal.Instant.compare
- [x] Temporal.Instant.prototype.constructor
- [x] Temporal.Instant.prototype[ @@toStringTag ]
- [x] Temporal.Instant.prototype.epochSeconds
- [x] Temporal.Instant.prototype.epochMilliseconds
- [x] Temporal.Instant.prototype.epochMicroseconds
- [x] Temporal.Instant.prototype.epochNanoseconds
- [x] Temporal.Instant.prototype.add
- [x] Temporal.Instant.prototype.subtract
- [x] Temporal.Instant.prototype.until
- [x] Temporal.Instant.prototype.since
- [x] Temporal.Instant.prototype.round
- [x] Temporal.Instant.prototype.equals
- [x] Temporal.Instant.prototype.toString
- [x] Temporal.Instant.prototype.toLocaleString
- [x] Temporal.Instant.prototype.toJSON
- [x] Temporal.Instant.prototype.valueOf
- [x] Temporal.Instant.prototype.toZonedDateTime
- [x] Temporal.Instant.prototype.toZonedDateTimeISO
- [x] Temporal.PlainYearMonth
- [x] Temporal.PlainYearMonth.from
- [x] Temporal.PlainYearMonth.compare
- [x] Temporal.PlainYearMonth.prototype.constructor
- [x] Temporal.PlainYearMonth.prototype[ @@toStringTag ]
- [x] Temporal.PlainYearMonth.prototype.calendar
- [x] Temporal.PlainYearMonth.prototype.year
- [x] Temporal.PlainYearMonth.prototype.month
- [x] Temporal.PlainYearMonth.prototype.monthCode
- [x] Temporal.PlainYearMonth.prototype.daysInYear
- [x] Temporal.PlainYearMonth.prototype.daysInMonth
- [x] Temporal.PlainYearMonth.prototype.monthsInYear
- [x] Temporal.PlainYearMonth.prototype.inLeapYear
- [x] Temporal.PlainYearMonth.prototype.with
- [x] Temporal.PlainYearMonth.prototype.add
- [x] Temporal.PlainYearMonth.prototype.subtract
- [x] Temporal.PlainYearMonth.prototype.until
- [x] Temporal.PlainYearMonth.prototype.since
- [x] Temporal.PlainYearMonth.prototype.equals
- [x] Temporal.PlainYearMonth.prototype.toString
- [x] Temporal.PlainYearMonth.prototype.toLocaleString
- [x] Temporal.PlainYearMonth.prototype.toJSON
- [x] Temporal.PlainYearMonth.prototype.valueOf
- [x] Temporal.PlainYearMonth.prototype.toPlainDate
- [x] Temporal.PlainYearMonth.prototype.getISOFields
- [x] Temporal.PlainMonthDay
- [x] Temporal.PlainMonthDay.from
- [x] Temporal.PlainMonthDay.prototype.constructor
- [x] Temporal.PlainMonthDay.prototype[ @@toStringTag ]
- [x] Temporal.PlainMonthDay.prototype.calendar
- [x] Temporal.PlainMonthDay.prototype.monthCode
- [x] Temporal.PlainMonthDay.prototype.day
- [x] Temporal.PlainMonthDay.prototype.with
- [x] Temporal.PlainMonthDay.prototype.equals
- [x] Temporal.PlainMonthDay.prototype.toString
- [x] Temporal.PlainMonthDay.prototype.toLocaleString
- [x] Temporal.PlainMonthDay.prototype.toJSON
- [x] Temporal.PlainMonthDay.prototype.valueOf
- [x] Temporal.PlainMonthDay.prototype.toPlainDate
- [x] Temporal.PlainMonthDay.prototype.getISOFields
- [x] Temporal.TimeZone
- [x] Temporal.TimeZone.from
- [x] Temporal.TimeZone.prototype.constructor
- [x] Temporal.TimeZone.prototype[ @@toStringTag ]
- [x] Temporal.TimeZone.prototype.id
- [x] Temporal.TimeZone.prototype.getOffsetNanosecondsFor
- [x] Temporal.TimeZone.prototype.getOffsetStringFor
- [x] Temporal.TimeZone.prototype.getPlainDateTimeFor
- [x] Temporal.TimeZone.prototype.getInstantFor
- [x] Temporal.TimeZone.prototype.getPossibleInstantsFor
- [x] Temporal.TimeZone.prototype.getNextTransition
- [x] Temporal.TimeZone.prototype.getPreviousTransition
- [x] Temporal.TimeZone.prototype.toString
- [x] Temporal.TimeZone.prototype.toJSON
- [x] Temporal.Calendar
- [x] Temporal.Calendar.from
- [x] Temporal.Calendar.prototype.constructor
- [x] Temporal.Calendar.prototype[ @@toStringTag ]
- [x] Temporal.Calendar.prototype.id
- [x] Temporal.Calendar.prototype.dateFromFields
- [x] Temporal.Calendar.prototype.yearMonthFromFields
- [x] Temporal.Calendar.prototype.monthDayFromFields
- [x] Temporal.Calendar.prototype.dateAdd
- [x] Temporal.Calendar.prototype.dateUntil
- [x] Temporal.Calendar.prototype.year
- [x] Temporal.Calendar.prototype.month
- [x] Temporal.Calendar.prototype.monthCode
- [x] Temporal.Calendar.prototype.day
- [x] Temporal.Calendar.prototype.dayOfWeek
- [x] Temporal.Calendar.prototype.dayOfYear
- [x] Temporal.Calendar.prototype.weekOfYear
- [x] Temporal.Calendar.prototype.daysInWeek
- [x] Temporal.Calendar.prototype.daysInMonth
- [x] Temporal.Calendar.prototype.daysInYear
- [x] Temporal.Calendar.prototype.monthsInYear
- [x] Temporal.Calendar.prototype.inLeapYear
- [x] Temporal.Calendar.prototype.fields
- [x] Temporal.Calendar.prototype.mergeFields
- [x] Temporal.Calendar.prototype.toString
- [x] Temporal.Calendar.prototype.toJSON

**Locale sensitive functions / function variants** (https://tc39.es/proposal-temporal/#locale-sensitive-functions)

- [ ] Temporal.Calendar.prototype.dateFromFields
- [ ] Temporal.Calendar.prototype.yearMonthFromFields
- [ ] Temporal.Calendar.prototype.monthDayFromFields
- [ ] Temporal.Calendar.prototype.dateAdd
- [ ] Temporal.Calendar.prototype.dateUntil
- [x] Temporal.Calendar.prototype.era
- [x] Temporal.Calendar.prototype.eraYear
- [ ] Temporal.Calendar.prototype.year
- [ ] Temporal.Calendar.prototype.month
- [ ] Temporal.Calendar.prototype.monthCode
- [ ] Temporal.Calendar.prototype.day
- [ ] Temporal.Calendar.prototype.dayOfWeek
- [ ] Temporal.Calendar.prototype.dayOfYear
- [ ] Temporal.Calendar.prototype.weekOfYear
- [ ] Temporal.Calendar.prototype.daysInWeek
- [ ] Temporal.Calendar.prototype.daysInMonth
- [ ] Temporal.Calendar.prototype.daysInYear
- [ ] Temporal.Calendar.prototype.monthsInYear
- [ ] Temporal.Calendar.prototype.inLeapYear
- [ ] Temporal.Calendar.prototype.fields
- [ ] Temporal.Calendar.prototype.mergeFields
- [ ] Temporal.Duration.prototype.toLocaleString
- [ ] Temporal.Instant.prototype.toLocaleString
- [ ] Temporal.PlainDate.prototype.toLocaleString
- [x] Temporal.PlainDate.prototype.era
- [x] Temporal.PlainDate.prototype.eraYear
- [ ] Temporal.PlainDateTime.prototype.toLocaleString
- [x] Temporal.PlainDateTime.prototype.era
- [x] Temporal.PlainDateTime.prototype.eraYear
- [ ] Temporal.PlainMonthDay.prototype.toLocaleString
- [ ] Temporal.PlainTime.prototype.toLocaleString
- [ ] Temporal.PlainYearMonth.prototype.toLocaleString
- [x] Temporal.PlainYearMonth.prototype.era
- [x] Temporal.PlainYearMonth.prototype.eraYear
- [ ] Temporal.ZonedDateTime.prototype.toLocaleString
- [x] Temporal.ZonedDateTime.prototype.era
- [x] Temporal.ZonedDateTime.prototype.eraYear

**Changes to `Intl.DateTimeFormat`** (https://tc39.es/proposal-temporal/#sec-properties-of-intl-datetimeformat-prototype-object)

- [ ] Intl.DateTimeFormat.prototype.formatToParts
- [ ] Intl.DateTimeFormat.prototype.formatRange
- [ ] Intl.DateTimeFormat.prototype.formatRangeToParts
- [ ] Intl.DateTimeFormat.prototype.resolvedOptions

---

Generated using the following code run in a browser console on the [spec page](https://tc39.es/proposal-temporal/), based on the code in https://github.com/tc39/test262/issues/3002:

```js
Array.from(document.querySelectorAll('[id^="sec-temporal."], [id^="sec-get-temporal."], [id$="-@@tostringtag"]'))
  .map((el) => {
    return el
      .querySelector('h1')
      .innerText
      .replace(/^[0-9\. ]*(?:get )?([^([]+)(\[[^\]]+])?.*/, '- [ ] $1$2')
      .trim();
  })
  .join('\n');
```

**Comment by ptomato** [comment]
You may be interested in the graph I made showing which parts of Temporal depend on which other parts: https://bugs.webkit.org/show_bug.cgi?id=223166#c2
