### ISSUE TITLE
LibJS: Intl progress tracking

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#9633]
Spec: https://tc39.es/ecma402/

- [x] Intl[ @@toStringTag ]
- [x] Intl.getCanonicalLocales
- [x] Intl.Collator
- [x] Intl.Collator.prototype
- [x] Intl.Collator.supportedLocalesOf
- [x] Intl.Collator.prototype.constructor
- [x] Intl.Collator.prototype [ @@toStringTag ]
- [ ] Intl.Collator.prototype.compare
- [x] Intl.Collator.prototype.resolvedOptions
- [x] Intl.DateTimeFormat
- [x] Intl.DateTimeFormat.prototype
- [x] Intl.DateTimeFormat.supportedLocalesOf
- [x] Intl.DateTimeFormat.prototype.constructor
- [x] Intl.DateTimeFormat.prototype [ @@toStringTag ]
- [x] Intl.DateTimeFormat.prototype.format
- [x] Intl.DateTimeFormat.prototype.formatToParts
- [x] Intl.DateTimeFormat.prototype.formatRange
- [x] Intl.DateTimeFormat.prototype.formatRangeToParts
- [x] Intl.DateTimeFormat.prototype.resolvedOptions
- [x] Intl.DisplayNames
- [x] Intl.DisplayNames.prototype
- [x] Intl.DisplayNames.supportedLocalesOf
- [x] Intl.DisplayNames.prototype.constructor
- [x] Intl.DisplayNames.prototype[ @@toStringTag ]
- [x] Intl.DisplayNames.prototype.of
- [x] Intl.DisplayNames.prototype.resolvedOptions
- [x] Intl.ListFormat
- [x] Intl.ListFormat.prototype
- [x] Intl.ListFormat.supportedLocalesOf
- [x] Intl.ListFormat.prototype.constructor
- [x] Intl.ListFormat.prototype [ @@toStringTag ]
- [x] Intl.ListFormat.prototype.format
- [x] Intl.ListFormat.prototype.formatToParts
- [x] Intl.ListFormat.prototype.resolvedOptions
- [x] Intl.Locale
- [x] Intl.Locale.prototype
- [x] Intl.Locale.prototype.constructor
- [x] Intl.Locale.prototype[ @@toStringTag ]
- [x] Intl.Locale.prototype.maximize
- [x] Intl.Locale.prototype.minimize
- [x] Intl.Locale.prototype.toString
- [x] Intl.Locale.prototype.baseName
- [x] Intl.Locale.prototype.calendar
- [x] Intl.Locale.prototype.caseFirst
- [x] Intl.Locale.prototype.collation
- [x] Intl.Locale.prototype.hourCycle
- [x] Intl.Locale.prototype.numeric
- [x] Intl.Locale.prototype.numberingSystem
- [x] Intl.Locale.prototype.language
- [x] Intl.Locale.prototype.script
- [x] Intl.Locale.prototype.region
- [x] Intl.NumberFormat
- [x] Intl.NumberFormat.prototype
- [x] Intl.NumberFormat.supportedLocalesOf
- [x] Intl.NumberFormat.prototype.constructor
- [x] Intl.NumberFormat.prototype [ @@toStringTag ]
- [x] Intl.NumberFormat.prototype.format
- [x] Intl.NumberFormat.prototype.formatToParts
- [x] Intl.NumberFormat.prototype.resolvedOptions
- [x] Intl.PluralRules
- [x] Intl.PluralRules.prototype
- [x] Intl.PluralRules.supportedLocalesOf
- [x] Intl.PluralRules.prototype.constructor
- [x] Intl.PluralRules.prototype [ @@toStringTag ]
- [x] Intl.PluralRules.prototype.select
- [x] Intl.PluralRules.prototype.resolvedOptions
- [x] Intl.RelativeTimeFormat
- [x] Intl.RelativeTimeFormat.prototype
- [x] Intl.RelativeTimeFormat.supportedLocalesOf
- [x] Intl.RelativeTimeFormat.prototype.constructor
- [x] Intl.RelativeTimeFormat.prototype[ @@toStringTag ]
- [x] Intl.RelativeTimeFormat.prototype.format
- [x] Intl.RelativeTimeFormat.prototype.formatToParts
- [x] Intl.RelativeTimeFormat.prototype.resolvedOptions
- [x] Intl.Segmenter
- [x] Intl.Segmenter.prototype
- [x] Intl.Segmenter.supportedLocalesOf
- [x] Intl.Segmenter.prototype.constructor
- [x] Intl.Segmenter.prototype [ @@toStringTag ]
- [x] Intl.Segmenter.prototype.segment
- [x] Intl.Segmenter.prototype.resolvedOptions"

**Comment by trflynn89** [comment]
If anyone happens to pick up `Intl.Collator`, this branch started work on that object: https://github.com/trflynn89/serenity/tree/intl_collator

Note the commit `LibUnicode: Parse and generate Unicode locale extension keywords` is wrong, that ended up not being the data we need to generate. The data we need is here: https://github.com/unicode-org/cldr-staging/tree/master/production/common/collation
Unfortunately that data doesn't exist in the JSON export, so we'll either need an XML parser or convince Unicode to export it.
